image: node:lts

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.build:
  stage: build
  cache:
    paths:
      - node_modules/.cache/
      - npm_cache/
  before_script:
    - npm config set cache npm_cache/
    - npm ci
    - npm --no-git-tag-version version $(git describe)
    - npm rebuild node-sass
  script:
    - npm run lint
    - npm run build-dev
  artifacts:
    paths:
      - dist/

.deploy:
  stage: deploy
  before_script:
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  script:
    - rsync -avz -e 'ssh -p2201' --delete dist/ $SFTP_SERVER

build:development:
  extends: .build
  environment:
    name: development

deploy:development:
  extends: .deploy
  needs:
    - build:development
  environment:
    name: development
  only:
    - master
    - ci

build:production:
  extends: .build
  environment:
    name: production
  only:
    - tags

deploy:production:
  extends: .deploy
  needs:
    - build:production
  environment:
    name: production
  only:
    - tags
  when: manual
