image: node:11

cache:
  paths:
    - node_modules/

production build:
  stage: build
  script:
    - npm install
    - npm run lint
    - npm run build -- --prod --env=prod --stats-json
  artifacts:
    paths:
      - dist/
